services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/opt/app/staticfiles:ro
      - ./media:/opt/app/media:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt:ro

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    command: gunicorn switchh.wsgi:application -b 0.0.0.0:8000 --workers=3
    depends_on:
      - db
    volumes:
      - ./staticfiles:/opt/app/staticfiles
      - ./media:/opt/app/media

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  postgres_data:
